### ISSUE TITLE
Impossible to instantiate more than one autocomplete component on the same page due to hard set #pac-input

### ISSUE THREAD

**Issue by born2discover** [chantouchsek/vuejs-google-maps#35]
Hello there and thank you for the component!

I've been using it in a project of mine and it works flawlessly.
Unfortunately I have recently run into an issue with the Autocomplete component.

It follows from the Autocomplete component's description in the readme that it can be used independently in an application. However, if you were to instantiate two or more instances of it, you'd get an error stating that you have a duplicate `#pac-input` id on the page.

After digging in, I found out that Autocomplete component hard sets that id on line [22](https://github.com/chantouchsek/vuejs-google-maps/blob/master/lib/components/Autocomplete.vue#L22) of `Autocomplete.vue`:

```html
<input id="pac-input" ...>
```

 and only referencces it once on line [111](https://github.com/chantouchsek/vuejs-google-maps/blob/master/lib/components/Autocomplete.vue#L111):

```js
 googleMapsReady () {
    let input = this.$el.querySelector('#pac-input')
    this.$_autocomplete = new window.google.maps.places.Autocomplete(input)
    ....
}
```

Considering that`googleMapsReady()` function is invoked by Ready mixin in its `mounted` hook, wouldn't it be better to use a `$ref` instead?
That would allow for multiple components to be rendered on the same page without any modifications to the underlying functionality.

**Comment by sctouch** [comment]
Fixed in release `v0.1.0`
