### ISSUE TITLE
Export loader

### ISSUE THREAD

**Issue by elyulka** [chantouchsek/vuejs-google-maps#63]
It would be great if library exported loader to be able to call `loader.ensureReady()` to be able to use google API outside of the library components.

**Comment by chantouchsek** [comment]
@elyulka tell me why do you need to use that function?

**Comment by elyulka** [comment]
@chantouchsek  We have custom Google Places autocompleter on the pages with and without Google Map and want to avoid double loading of Google SDK via this library and custom component. Exported loader gives possibility to call `loader.ensureReady()` in the `mounted()` hook and safely use `google.*` API.

**Comment by sctouch** [comment]
@elyulka thanks. i will check PR above.

**Comment by sctouch** [comment]
It will available in next release.
